"""Create ProjectFile table and link to Project

Revision ID: 182ada5004ce
Revises: b94a1430dce0
Create Date: 2026-01-10 06:40:26.673197+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '182ada5004ce'
down_revision: str = 'b94a1430dce0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('original_filename', sa.String(length=500), nullable=False, comment='The original name of the file as uploaded by the user.'),
    sa.Column('saved_path', sa.String(length=500), nullable=False, comment="The path to the file on the server's storage, usually with a randomized name."),
    sa.Column('file_type', sa.Enum('MAIN_REPORT', 'SUPPLEMENTARY', 'THUMBNAIL', name='filetype'), nullable=False, comment='The role of the file in the project.'),
    sa.Column('mime_type', sa.String(length=100), nullable=True, comment="The MIME type of the file, e.g., 'application/pdf'."),
    sa.Column('file_size', sa.Integer(), nullable=True, comment='File size in bytes.'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('saved_path')
    )
    with op.batch_alter_table('project_files', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_files_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_files_project_id'), ['project_id'], unique=False)

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('supplementary_files')
        batch_op.drop_column('pdf_file_size')
        batch_op.drop_column('pdf_file_path')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pdf_file_path', sa.VARCHAR(length=500), autoincrement=False, nullable=True, comment='Path to uploaded PDF file'))
        batch_op.add_column(sa.Column('pdf_file_size', sa.INTEGER(), autoincrement=False, nullable=True, comment='File size in bytes'))
        batch_op.add_column(sa.Column('supplementary_files', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True, comment='Additional file paths (images, data, etc.)'))

    with op.batch_alter_table('project_files', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_files_project_id'))
        batch_op.drop_index(batch_op.f('ix_project_files_id'))

    op.drop_table('project_files')
    # ### end Alembic commands ###