"""initial

Revision ID: 442648875932
Revises: 
Create Date: 2026-01-06 14:04:16.835275+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '442648875932'
down_revision: str = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=False, comment="Role: 'student' or 'dosen'"),
    sa.Column('student_id', sa.String(length=50), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('title', sa.String(length=50), nullable=True, comment='Academic title: Dr., Prof., etc.'),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_role'), ['role'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_student_id'), ['student_id'], unique=True)

    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('abstract', sa.Text(), nullable=True),
    sa.Column('abstract_preview', sa.String(length=300), nullable=True, comment='Truncated abstract for search results'),
    sa.Column('authors', sa.ARRAY(sa.String()), nullable=True, comment='List of author names'),
    sa.Column('tags', sa.ARRAY(sa.String()), nullable=True, comment='Topics: ML, NLP, Computer Vision, etc.'),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('semester', sa.String(length=20), nullable=True, comment="'Ganjil' or 'Genap'"),
    sa.Column('class_name', sa.String(length=100), nullable=True),
    sa.Column('course_code', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('ONGOING', 'COMPLETED', 'ARCHIVED', name='projectstatus'), nullable=False),
    sa.Column('privacy_level', sa.Enum('PRIVATE', 'ADVISOR', 'CLASS', 'PUBLIC', name='privacylevel'), nullable=False),
    sa.Column('pdf_file_path', sa.String(length=500), nullable=True, comment='Path to uploaded PDF file'),
    sa.Column('pdf_file_size', sa.Integer(), nullable=True, comment='File size in bytes'),
    sa.Column('code_repo_url', sa.String(length=500), nullable=True, comment='GitHub/GitLab repository URL'),
    sa.Column('dataset_url', sa.String(length=500), nullable=True, comment='Link to dataset (if publicly available)'),
    sa.Column('supplementary_files', sa.ARRAY(sa.String()), nullable=True, comment='Additional file paths (images, data, etc.)'),
    sa.Column('uploaded_by', sa.Integer(), nullable=False),
    sa.Column('advisor_id', sa.Integer(), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('download_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['advisor_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_projects_advisor_id'), ['advisor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_projects_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_projects_privacy_level'), ['privacy_level'], unique=False)
        batch_op.create_index(batch_op.f('ix_projects_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_projects_tags'), ['tags'], unique=False)
        batch_op.create_index(batch_op.f('ix_projects_title'), ['title'], unique=False)
        batch_op.create_index(batch_op.f('ix_projects_uploaded_by'), ['uploaded_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_projects_year'), ['year'], unique=False)

    op.create_table('access_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('requester_id', sa.Integer(), nullable=False, comment='User requesting access (usually a dosen)'),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'DENIED', 'REVOKED', name='accessrequeststatus'), nullable=False),
    sa.Column('message', sa.Text(), nullable=True, comment='Optional message from requester explaining why they need access'),
    sa.Column('response_message', sa.Text(), nullable=True, comment='Optional message from project owner when approving/denying'),
    sa.Column('requested_at', sa.DateTime(), nullable=False),
    sa.Column('responded_at', sa.DateTime(), nullable=True, comment='When the request was approved/denied'),
    sa.Column('expires_at', sa.DateTime(), nullable=True, comment='When access expires (optional)'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'requester_id', name='uq_project_requester')
    )
    with op.batch_alter_table('access_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_access_requests_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_access_requests_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_access_requests_requested_at'), ['requested_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_access_requests_requester_id'), ['requester_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_access_requests_status'), ['status'], unique=False)

    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('access_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_access_requests_status'))
        batch_op.drop_index(batch_op.f('ix_access_requests_requester_id'))
        batch_op.drop_index(batch_op.f('ix_access_requests_requested_at'))
        batch_op.drop_index(batch_op.f('ix_access_requests_project_id'))
        batch_op.drop_index(batch_op.f('ix_access_requests_id'))

    op.drop_table('access_requests')
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projects_year'))
        batch_op.drop_index(batch_op.f('ix_projects_uploaded_by'))
        batch_op.drop_index(batch_op.f('ix_projects_title'))
        batch_op.drop_index(batch_op.f('ix_projects_tags'))
        batch_op.drop_index(batch_op.f('ix_projects_status'))
        batch_op.drop_index(batch_op.f('ix_projects_privacy_level'))
        batch_op.drop_index(batch_op.f('ix_projects_id'))
        batch_op.drop_index(batch_op.f('ix_projects_advisor_id'))

    op.drop_table('projects')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_student_id'))
        batch_op.drop_index(batch_op.f('ix_users_role'))
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###