"""Add lecturer name to projects table

Revision ID: 91f711b9c9c4
Revises: 182ada5004ce
Create Date: 2026-01-10 14:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91f711b9c9c4'
down_revision: str = '182ada5004ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('lecturer_name', sa.String(length=200), nullable=True, comment="Nama Dosen"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'lecturer_name')
    # ### end Alembic commands ###