"""Add uuid to user

Revision ID: add_uuid_to_user
Revises: 442648875932
Create Date: 2026-01-08 10:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import uuid

# revision identifiers, used by Alembic.
revision: str = 'add_uuid_to_user'
down_revision: Union[str, None] = '442648875932'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uuid', sa.UUID(), nullable=True))
        batch_op.create_unique_constraint("uq_users_uuid", ["uuid"])

    # Populate uuid for existing users
    bind = op.get_bind()
    session = sa.orm.Session(bind=bind)
    try:
        users = session.execute(sa.text("SELECT id FROM users WHERE uuid IS NULL")).fetchall()
        for user in users:
            session.execute(
                sa.text("UPDATE users SET uuid = :uuid WHERE id = :id"),
                {"uuid": str(uuid.uuid4()), "id": user.id},
            )
        session.commit()
    finally:
        session.close()

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('uuid', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint("uq_users_uuid", type_='unique')
        batch_op.drop_column('uuid')

    # ### end Alembic commands ###
