"""Create courses table

Revision ID: create_courses_table
Revises: 91f711b9c9c4
Create Date: 2026-01-10 16:10:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'create_courses_table'
down_revision: Union[str, None] = '91f711b9c9c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('course_code', sa.String(length=20), nullable=False, comment='Course code (e.g., CS101, ML202)'),
        sa.Column('course_name', sa.String(length=200), nullable=False, comment='Full course name'),
        sa.Column('semester', sa.String(length=20), nullable=False, comment="'Ganjil' or 'Genap'"),
        sa.Column('year', sa.Integer(), nullable=False),
        sa.Column('lecturer_id', sa.Integer(), nullable=False, comment='Main lecturer/creator of this course'),
        sa.Column('created_by', sa.Integer(), nullable=False, comment='User who created this course record'),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['lecturer_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_courses_course_code'), ['course_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_courses_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_courses_lecturer_id'), ['lecturer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_courses_year'), ['year'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_courses_year'))
        batch_op.drop_index(batch_op.f('ix_courses_lecturer_id'))
        batch_op.drop_index(batch_op.f('ix_courses_id'))
        batch_op.drop_index(batch_op.f('ix_courses_course_code'))

    op.drop_table('courses')
    # ### end Alembic commands ###